// app/layout.js
import "../styles/globals.css";
import { HoveredModelProvider } from "../components/HoveredModelContext";
import ModelImageCursor from "../components/ModelImageCursor";
import SmoothScroll from "../components/SmoothScroll";
// Leave the tab and come back and the page resolves rather than just being
// there. Mounted at the root so it covers every route, not only home.
import ReturnReveal from "../components/ReturnReveal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SmoothScroll />
        <ReturnReveal />
        <HoveredModelProvider>
          {children}
          <ModelImageCursor />
        </HoveredModelProvider>
      </body>
    </html>
  );
}
