// app/layout.js
import "../styles/globals.css";
import { HoveredModelProvider } from "../components/HoveredModelContext";
import ModelImageCursor from "../components/ModelImageCursor";
import SmoothScroll from "../components/SmoothScroll";
import TransitionProvider from "@/providers/TransitionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SmoothScroll />
        <TransitionProvider>
          <HoveredModelProvider>
            {children}
            <ModelImageCursor />
          </HoveredModelProvider>
        </TransitionProvider>
      </body>
    </html>
  );
}
